### ISSUE TITLE
Create Database Relationship Diagram - Digital

### ISSUE THREAD

**Issue by mapage2** [nFinitySolutionsdev/Prometheus#7]
Digitize the rough sketch created in Prometheus #6.

Save for documentation purposes

**Comment by zerosADnn** [comment]
Given that you've already created a sketch, it's just a matter of review, edits, and approval. 3 days to factor in what we are doing outside of this.

**Comment by mapage2** [comment]
Created digital Entity Relationship diagram.
Posted in Allo chat awaiting approval from Dwain and Dylan
